name: /nfs/stak/users/viswansi/hpc-share/morl-baselines-env
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - icu=78.2
  - ld_impl_linux-64=2.45
  - libexpat=2.7.3
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libsqlite=3.51.2
  - libstdcxx=15.2.0
  - libuuid=2.41.3
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.6.0
  - pip=25.3
  - python=3.10.19
  - readline=8.3
  - setuptools=80.9.0
  - tk=8.6.13
  - tzdata=2025c
  - wheel=0.45.1
  - zstd=1.5.7
  - pip:
      - about-time==4.2.1
      - absl-py==2.3.1
      - alive-progress==3.3.0
      - annotated-types==0.7.0
      - autograd==1.8.0
      - certifi==2026.1.4
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cloudpickle==3.1.2
      - cma==4.4.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - deprecated==1.3.1
      - etils==1.13.0
      - farama-notifications==0.0.4
      - filelock==3.20.0
      - fonttools==4.61.1
      - fsspec==2026.1.0
      - gitdb==4.0.12
      - gitpython==3.1.46
      - glfw==2.10.0
      - graphemeu==0.7.2
      - gymnasium==1.2.3
      - idna==3.11
      - imageio==2.37.2
      - importlib-resources==6.5.2
      - jinja2==3.1.6
      - kiwisolver==1.4.9
      - markupsafe==2.1.5
      - matplotlib==3.10.8
      - mo-gymnasium==1.3.1
      - moocore==0.2.0
      - mpmath==1.3.0
      - mujoco==3.4.0
      - networkx==3.4.2
      - numpy==1.26.4
      - packaging==25.0
      - pillow==12.1.0
      - platformdirs==4.5.1
      - protobuf==6.33.4
      - pycparser==2.23
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pygame==2.6.1
      - pymoo==0.6.1.6
      - pyopengl==3.1.10
      - pyparsing==3.3.1
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.3
      - requests==2.32.5
      - scipy==1.15.3
      - sentry-sdk==2.49.0
      - six==1.17.0
      - smmap==5.0.2
      - sympy==1.14.0
      - torch
      - torchvision
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - urllib3==2.6.3
      - wandb==0.24.0
      - wrapt==2.0.1
      - zipp==3.23.0
prefix: /nfs/stak/users/viswansi/hpc-share/morl-baselines-env
